package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Thursday, May 14, 2026 2:14:09 AM SGT
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
